// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: representacaoexternaBuffer/Gerenciamento.proto

package representacaoexternaBuffer;

public final class GerenciamentoOuterClass {
  private GerenciamentoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GerenciamentoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:representacaoexternaBuffer.Gerenciamento)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string titulo = 1;</code>
     */
    boolean hasTitulo();
    /**
     * <code>required string titulo = 1;</code>
     */
    java.lang.String getTitulo();
    /**
     * <code>required string titulo = 1;</code>
     */
    com.google.protobuf.ByteString
        getTituloBytes();

    /**
     * <code>required string autor = 2;</code>
     */
    boolean hasAutor();
    /**
     * <code>required string autor = 2;</code>
     */
    java.lang.String getAutor();
    /**
     * <code>required string autor = 2;</code>
     */
    com.google.protobuf.ByteString
        getAutorBytes();

    /**
     * <code>required string cantor = 3;</code>
     */
    boolean hasCantor();
    /**
     * <code>required string cantor = 3;</code>
     */
    java.lang.String getCantor();
    /**
     * <code>required string cantor = 3;</code>
     */
    com.google.protobuf.ByteString
        getCantorBytes();

    /**
     * <code>required int32 ano = 4;</code>
     */
    boolean hasAno();
    /**
     * <code>required int32 ano = 4;</code>
     */
    int getAno();

    /**
     * <code>required int32 num_pagina = 5;</code>
     */
    boolean hasNumPagina();
    /**
     * <code>required int32 num_pagina = 5;</code>
     */
    int getNumPagina();

    /**
     * <code>required string isbn = 6;</code>
     */
    boolean hasIsbn();
    /**
     * <code>required string isbn = 6;</code>
     */
    java.lang.String getIsbn();
    /**
     * <code>required string isbn = 6;</code>
     */
    com.google.protobuf.ByteString
        getIsbnBytes();

    /**
     * <code>required float peso = 7;</code>
     */
    boolean hasPeso();
    /**
     * <code>required float peso = 7;</code>
     */
    float getPeso();

    /**
     * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
     */
    boolean hasDim();
    /**
     * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
     */
    representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao getDim();
    /**
     * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
     */
    representacaoexternaBuffer.GerenciamentoOuterClass.DimensaoOrBuilder getDimOrBuilder();

    /**
     * <code>required string album = 9;</code>
     */
    boolean hasAlbum();
    /**
     * <code>required string album = 9;</code>
     */
    java.lang.String getAlbum();
    /**
     * <code>required string album = 9;</code>
     */
    com.google.protobuf.ByteString
        getAlbumBytes();

    /**
     * <code>required string data_lancamento = 10;</code>
     */
    boolean hasDataLancamento();
    /**
     * <code>required string data_lancamento = 10;</code>
     */
    java.lang.String getDataLancamento();
    /**
     * <code>required string data_lancamento = 10;</code>
     */
    com.google.protobuf.ByteString
        getDataLancamentoBytes();
  }
  /**
   * Protobuf type {@code representacaoexternaBuffer.Gerenciamento}
   */
  public  static final class Gerenciamento extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:representacaoexternaBuffer.Gerenciamento)
      GerenciamentoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Gerenciamento.newBuilder() to construct.
    private Gerenciamento(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Gerenciamento() {
      titulo_ = "";
      autor_ = "";
      cantor_ = "";
      ano_ = 0;
      numPagina_ = 0;
      isbn_ = "";
      peso_ = 0F;
      album_ = "";
      dataLancamento_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Gerenciamento(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              titulo_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              autor_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              cantor_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ano_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              numPagina_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              isbn_ = bs;
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              peso_ = input.readFloat();
              break;
            }
            case 66: {
              representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.Builder subBuilder = null;
              if (((bitField0_ & 0x00000080) == 0x00000080)) {
                subBuilder = dim_.toBuilder();
              }
              dim_ = input.readMessage(representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dim_);
                dim_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000080;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              album_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              dataLancamento_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return representacaoexternaBuffer.GerenciamentoOuterClass.internal_static_representacaoexternaBuffer_Gerenciamento_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return representacaoexternaBuffer.GerenciamentoOuterClass.internal_static_representacaoexternaBuffer_Gerenciamento_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento.class, representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento.Builder.class);
    }

    private int bitField0_;
    public static final int TITULO_FIELD_NUMBER = 1;
    private volatile java.lang.Object titulo_;
    /**
     * <code>required string titulo = 1;</code>
     */
    public boolean hasTitulo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string titulo = 1;</code>
     */
    public java.lang.String getTitulo() {
      java.lang.Object ref = titulo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          titulo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string titulo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTituloBytes() {
      java.lang.Object ref = titulo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        titulo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTOR_FIELD_NUMBER = 2;
    private volatile java.lang.Object autor_;
    /**
     * <code>required string autor = 2;</code>
     */
    public boolean hasAutor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string autor = 2;</code>
     */
    public java.lang.String getAutor() {
      java.lang.Object ref = autor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          autor_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string autor = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAutorBytes() {
      java.lang.Object ref = autor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        autor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CANTOR_FIELD_NUMBER = 3;
    private volatile java.lang.Object cantor_;
    /**
     * <code>required string cantor = 3;</code>
     */
    public boolean hasCantor() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string cantor = 3;</code>
     */
    public java.lang.String getCantor() {
      java.lang.Object ref = cantor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cantor_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string cantor = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCantorBytes() {
      java.lang.Object ref = cantor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cantor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANO_FIELD_NUMBER = 4;
    private int ano_;
    /**
     * <code>required int32 ano = 4;</code>
     */
    public boolean hasAno() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 ano = 4;</code>
     */
    public int getAno() {
      return ano_;
    }

    public static final int NUM_PAGINA_FIELD_NUMBER = 5;
    private int numPagina_;
    /**
     * <code>required int32 num_pagina = 5;</code>
     */
    public boolean hasNumPagina() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 num_pagina = 5;</code>
     */
    public int getNumPagina() {
      return numPagina_;
    }

    public static final int ISBN_FIELD_NUMBER = 6;
    private volatile java.lang.Object isbn_;
    /**
     * <code>required string isbn = 6;</code>
     */
    public boolean hasIsbn() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string isbn = 6;</code>
     */
    public java.lang.String getIsbn() {
      java.lang.Object ref = isbn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          isbn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string isbn = 6;</code>
     */
    public com.google.protobuf.ByteString
        getIsbnBytes() {
      java.lang.Object ref = isbn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isbn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PESO_FIELD_NUMBER = 7;
    private float peso_;
    /**
     * <code>required float peso = 7;</code>
     */
    public boolean hasPeso() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required float peso = 7;</code>
     */
    public float getPeso() {
      return peso_;
    }

    public static final int DIM_FIELD_NUMBER = 8;
    private representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao dim_;
    /**
     * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
     */
    public boolean hasDim() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
     */
    public representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao getDim() {
      return dim_ == null ? representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.getDefaultInstance() : dim_;
    }
    /**
     * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
     */
    public representacaoexternaBuffer.GerenciamentoOuterClass.DimensaoOrBuilder getDimOrBuilder() {
      return dim_ == null ? representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.getDefaultInstance() : dim_;
    }

    public static final int ALBUM_FIELD_NUMBER = 9;
    private volatile java.lang.Object album_;
    /**
     * <code>required string album = 9;</code>
     */
    public boolean hasAlbum() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string album = 9;</code>
     */
    public java.lang.String getAlbum() {
      java.lang.Object ref = album_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          album_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string album = 9;</code>
     */
    public com.google.protobuf.ByteString
        getAlbumBytes() {
      java.lang.Object ref = album_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        album_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_LANCAMENTO_FIELD_NUMBER = 10;
    private volatile java.lang.Object dataLancamento_;
    /**
     * <code>required string data_lancamento = 10;</code>
     */
    public boolean hasDataLancamento() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required string data_lancamento = 10;</code>
     */
    public java.lang.String getDataLancamento() {
      java.lang.Object ref = dataLancamento_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataLancamento_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string data_lancamento = 10;</code>
     */
    public com.google.protobuf.ByteString
        getDataLancamentoBytes() {
      java.lang.Object ref = dataLancamento_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataLancamento_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTitulo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAutor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCantor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAno()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNumPagina()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsbn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPeso()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDim()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlbum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataLancamento()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getDim().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, titulo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, autor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cantor_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, ano_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, numPagina_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, isbn_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFloat(7, peso_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, getDim());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, album_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, dataLancamento_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, titulo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, autor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cantor_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, ano_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, numPagina_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, isbn_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, peso_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getDim());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, album_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, dataLancamento_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento)) {
        return super.equals(obj);
      }
      representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento other = (representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento) obj;

      boolean result = true;
      result = result && (hasTitulo() == other.hasTitulo());
      if (hasTitulo()) {
        result = result && getTitulo()
            .equals(other.getTitulo());
      }
      result = result && (hasAutor() == other.hasAutor());
      if (hasAutor()) {
        result = result && getAutor()
            .equals(other.getAutor());
      }
      result = result && (hasCantor() == other.hasCantor());
      if (hasCantor()) {
        result = result && getCantor()
            .equals(other.getCantor());
      }
      result = result && (hasAno() == other.hasAno());
      if (hasAno()) {
        result = result && (getAno()
            == other.getAno());
      }
      result = result && (hasNumPagina() == other.hasNumPagina());
      if (hasNumPagina()) {
        result = result && (getNumPagina()
            == other.getNumPagina());
      }
      result = result && (hasIsbn() == other.hasIsbn());
      if (hasIsbn()) {
        result = result && getIsbn()
            .equals(other.getIsbn());
      }
      result = result && (hasPeso() == other.hasPeso());
      if (hasPeso()) {
        result = result && (
            java.lang.Float.floatToIntBits(getPeso())
            == java.lang.Float.floatToIntBits(
                other.getPeso()));
      }
      result = result && (hasDim() == other.hasDim());
      if (hasDim()) {
        result = result && getDim()
            .equals(other.getDim());
      }
      result = result && (hasAlbum() == other.hasAlbum());
      if (hasAlbum()) {
        result = result && getAlbum()
            .equals(other.getAlbum());
      }
      result = result && (hasDataLancamento() == other.hasDataLancamento());
      if (hasDataLancamento()) {
        result = result && getDataLancamento()
            .equals(other.getDataLancamento());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTitulo()) {
        hash = (37 * hash) + TITULO_FIELD_NUMBER;
        hash = (53 * hash) + getTitulo().hashCode();
      }
      if (hasAutor()) {
        hash = (37 * hash) + AUTOR_FIELD_NUMBER;
        hash = (53 * hash) + getAutor().hashCode();
      }
      if (hasCantor()) {
        hash = (37 * hash) + CANTOR_FIELD_NUMBER;
        hash = (53 * hash) + getCantor().hashCode();
      }
      if (hasAno()) {
        hash = (37 * hash) + ANO_FIELD_NUMBER;
        hash = (53 * hash) + getAno();
      }
      if (hasNumPagina()) {
        hash = (37 * hash) + NUM_PAGINA_FIELD_NUMBER;
        hash = (53 * hash) + getNumPagina();
      }
      if (hasIsbn()) {
        hash = (37 * hash) + ISBN_FIELD_NUMBER;
        hash = (53 * hash) + getIsbn().hashCode();
      }
      if (hasPeso()) {
        hash = (37 * hash) + PESO_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getPeso());
      }
      if (hasDim()) {
        hash = (37 * hash) + DIM_FIELD_NUMBER;
        hash = (53 * hash) + getDim().hashCode();
      }
      if (hasAlbum()) {
        hash = (37 * hash) + ALBUM_FIELD_NUMBER;
        hash = (53 * hash) + getAlbum().hashCode();
      }
      if (hasDataLancamento()) {
        hash = (37 * hash) + DATA_LANCAMENTO_FIELD_NUMBER;
        hash = (53 * hash) + getDataLancamento().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parseFrom(data);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parseFrom(data, extensionRegistry);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parseFrom(data);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code representacaoexternaBuffer.Gerenciamento}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:representacaoexternaBuffer.Gerenciamento)
        representacaoexternaBuffer.GerenciamentoOuterClass.GerenciamentoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return representacaoexternaBuffer.GerenciamentoOuterClass.internal_static_representacaoexternaBuffer_Gerenciamento_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return representacaoexternaBuffer.GerenciamentoOuterClass.internal_static_representacaoexternaBuffer_Gerenciamento_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento.class, representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento.Builder.class);
      }

      // Construct using representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDimFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        titulo_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        autor_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        cantor_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        ano_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        numPagina_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        isbn_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        peso_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        if (dimBuilder_ == null) {
          dim_ = null;
        } else {
          dimBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        album_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        dataLancamento_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return representacaoexternaBuffer.GerenciamentoOuterClass.internal_static_representacaoexternaBuffer_Gerenciamento_descriptor;
      }

      @java.lang.Override
      public representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento getDefaultInstanceForType() {
        return representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento.getDefaultInstance();
      }

      @java.lang.Override
      public representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento build() {
        representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento buildPartial() {
        representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento result = new representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.titulo_ = titulo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.autor_ = autor_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cantor_ = cantor_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ano_ = ano_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.numPagina_ = numPagina_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.isbn_ = isbn_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.peso_ = peso_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (dimBuilder_ == null) {
          result.dim_ = dim_;
        } else {
          result.dim_ = dimBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.album_ = album_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.dataLancamento_ = dataLancamento_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento) {
          return mergeFrom((representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento other) {
        if (other == representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento.getDefaultInstance()) return this;
        if (other.hasTitulo()) {
          bitField0_ |= 0x00000001;
          titulo_ = other.titulo_;
          onChanged();
        }
        if (other.hasAutor()) {
          bitField0_ |= 0x00000002;
          autor_ = other.autor_;
          onChanged();
        }
        if (other.hasCantor()) {
          bitField0_ |= 0x00000004;
          cantor_ = other.cantor_;
          onChanged();
        }
        if (other.hasAno()) {
          setAno(other.getAno());
        }
        if (other.hasNumPagina()) {
          setNumPagina(other.getNumPagina());
        }
        if (other.hasIsbn()) {
          bitField0_ |= 0x00000020;
          isbn_ = other.isbn_;
          onChanged();
        }
        if (other.hasPeso()) {
          setPeso(other.getPeso());
        }
        if (other.hasDim()) {
          mergeDim(other.getDim());
        }
        if (other.hasAlbum()) {
          bitField0_ |= 0x00000100;
          album_ = other.album_;
          onChanged();
        }
        if (other.hasDataLancamento()) {
          bitField0_ |= 0x00000200;
          dataLancamento_ = other.dataLancamento_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTitulo()) {
          return false;
        }
        if (!hasAutor()) {
          return false;
        }
        if (!hasCantor()) {
          return false;
        }
        if (!hasAno()) {
          return false;
        }
        if (!hasNumPagina()) {
          return false;
        }
        if (!hasIsbn()) {
          return false;
        }
        if (!hasPeso()) {
          return false;
        }
        if (!hasDim()) {
          return false;
        }
        if (!hasAlbum()) {
          return false;
        }
        if (!hasDataLancamento()) {
          return false;
        }
        if (!getDim().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object titulo_ = "";
      /**
       * <code>required string titulo = 1;</code>
       */
      public boolean hasTitulo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string titulo = 1;</code>
       */
      public java.lang.String getTitulo() {
        java.lang.Object ref = titulo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            titulo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string titulo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTituloBytes() {
        java.lang.Object ref = titulo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          titulo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string titulo = 1;</code>
       */
      public Builder setTitulo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        titulo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string titulo = 1;</code>
       */
      public Builder clearTitulo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        titulo_ = getDefaultInstance().getTitulo();
        onChanged();
        return this;
      }
      /**
       * <code>required string titulo = 1;</code>
       */
      public Builder setTituloBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        titulo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object autor_ = "";
      /**
       * <code>required string autor = 2;</code>
       */
      public boolean hasAutor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string autor = 2;</code>
       */
      public java.lang.String getAutor() {
        java.lang.Object ref = autor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            autor_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string autor = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAutorBytes() {
        java.lang.Object ref = autor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          autor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string autor = 2;</code>
       */
      public Builder setAutor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        autor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string autor = 2;</code>
       */
      public Builder clearAutor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        autor_ = getDefaultInstance().getAutor();
        onChanged();
        return this;
      }
      /**
       * <code>required string autor = 2;</code>
       */
      public Builder setAutorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        autor_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cantor_ = "";
      /**
       * <code>required string cantor = 3;</code>
       */
      public boolean hasCantor() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string cantor = 3;</code>
       */
      public java.lang.String getCantor() {
        java.lang.Object ref = cantor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cantor_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string cantor = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCantorBytes() {
        java.lang.Object ref = cantor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cantor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string cantor = 3;</code>
       */
      public Builder setCantor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        cantor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string cantor = 3;</code>
       */
      public Builder clearCantor() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cantor_ = getDefaultInstance().getCantor();
        onChanged();
        return this;
      }
      /**
       * <code>required string cantor = 3;</code>
       */
      public Builder setCantorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        cantor_ = value;
        onChanged();
        return this;
      }

      private int ano_ ;
      /**
       * <code>required int32 ano = 4;</code>
       */
      public boolean hasAno() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 ano = 4;</code>
       */
      public int getAno() {
        return ano_;
      }
      /**
       * <code>required int32 ano = 4;</code>
       */
      public Builder setAno(int value) {
        bitField0_ |= 0x00000008;
        ano_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ano = 4;</code>
       */
      public Builder clearAno() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ano_ = 0;
        onChanged();
        return this;
      }

      private int numPagina_ ;
      /**
       * <code>required int32 num_pagina = 5;</code>
       */
      public boolean hasNumPagina() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 num_pagina = 5;</code>
       */
      public int getNumPagina() {
        return numPagina_;
      }
      /**
       * <code>required int32 num_pagina = 5;</code>
       */
      public Builder setNumPagina(int value) {
        bitField0_ |= 0x00000010;
        numPagina_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 num_pagina = 5;</code>
       */
      public Builder clearNumPagina() {
        bitField0_ = (bitField0_ & ~0x00000010);
        numPagina_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object isbn_ = "";
      /**
       * <code>required string isbn = 6;</code>
       */
      public boolean hasIsbn() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string isbn = 6;</code>
       */
      public java.lang.String getIsbn() {
        java.lang.Object ref = isbn_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            isbn_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string isbn = 6;</code>
       */
      public com.google.protobuf.ByteString
          getIsbnBytes() {
        java.lang.Object ref = isbn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          isbn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string isbn = 6;</code>
       */
      public Builder setIsbn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        isbn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string isbn = 6;</code>
       */
      public Builder clearIsbn() {
        bitField0_ = (bitField0_ & ~0x00000020);
        isbn_ = getDefaultInstance().getIsbn();
        onChanged();
        return this;
      }
      /**
       * <code>required string isbn = 6;</code>
       */
      public Builder setIsbnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        isbn_ = value;
        onChanged();
        return this;
      }

      private float peso_ ;
      /**
       * <code>required float peso = 7;</code>
       */
      public boolean hasPeso() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required float peso = 7;</code>
       */
      public float getPeso() {
        return peso_;
      }
      /**
       * <code>required float peso = 7;</code>
       */
      public Builder setPeso(float value) {
        bitField0_ |= 0x00000040;
        peso_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float peso = 7;</code>
       */
      public Builder clearPeso() {
        bitField0_ = (bitField0_ & ~0x00000040);
        peso_ = 0F;
        onChanged();
        return this;
      }

      private representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao dim_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao, representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.Builder, representacaoexternaBuffer.GerenciamentoOuterClass.DimensaoOrBuilder> dimBuilder_;
      /**
       * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
       */
      public boolean hasDim() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
       */
      public representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao getDim() {
        if (dimBuilder_ == null) {
          return dim_ == null ? representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.getDefaultInstance() : dim_;
        } else {
          return dimBuilder_.getMessage();
        }
      }
      /**
       * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
       */
      public Builder setDim(representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao value) {
        if (dimBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dim_ = value;
          onChanged();
        } else {
          dimBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
       */
      public Builder setDim(
          representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.Builder builderForValue) {
        if (dimBuilder_ == null) {
          dim_ = builderForValue.build();
          onChanged();
        } else {
          dimBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
       */
      public Builder mergeDim(representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao value) {
        if (dimBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              dim_ != null &&
              dim_ != representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.getDefaultInstance()) {
            dim_ =
              representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.newBuilder(dim_).mergeFrom(value).buildPartial();
          } else {
            dim_ = value;
          }
          onChanged();
        } else {
          dimBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
       */
      public Builder clearDim() {
        if (dimBuilder_ == null) {
          dim_ = null;
          onChanged();
        } else {
          dimBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
       */
      public representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.Builder getDimBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getDimFieldBuilder().getBuilder();
      }
      /**
       * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
       */
      public representacaoexternaBuffer.GerenciamentoOuterClass.DimensaoOrBuilder getDimOrBuilder() {
        if (dimBuilder_ != null) {
          return dimBuilder_.getMessageOrBuilder();
        } else {
          return dim_ == null ?
              representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.getDefaultInstance() : dim_;
        }
      }
      /**
       * <code>required .representacaoexternaBuffer.Dimensao dim = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao, representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.Builder, representacaoexternaBuffer.GerenciamentoOuterClass.DimensaoOrBuilder> 
          getDimFieldBuilder() {
        if (dimBuilder_ == null) {
          dimBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao, representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.Builder, representacaoexternaBuffer.GerenciamentoOuterClass.DimensaoOrBuilder>(
                  getDim(),
                  getParentForChildren(),
                  isClean());
          dim_ = null;
        }
        return dimBuilder_;
      }

      private java.lang.Object album_ = "";
      /**
       * <code>required string album = 9;</code>
       */
      public boolean hasAlbum() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required string album = 9;</code>
       */
      public java.lang.String getAlbum() {
        java.lang.Object ref = album_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            album_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string album = 9;</code>
       */
      public com.google.protobuf.ByteString
          getAlbumBytes() {
        java.lang.Object ref = album_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          album_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string album = 9;</code>
       */
      public Builder setAlbum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        album_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string album = 9;</code>
       */
      public Builder clearAlbum() {
        bitField0_ = (bitField0_ & ~0x00000100);
        album_ = getDefaultInstance().getAlbum();
        onChanged();
        return this;
      }
      /**
       * <code>required string album = 9;</code>
       */
      public Builder setAlbumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        album_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataLancamento_ = "";
      /**
       * <code>required string data_lancamento = 10;</code>
       */
      public boolean hasDataLancamento() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required string data_lancamento = 10;</code>
       */
      public java.lang.String getDataLancamento() {
        java.lang.Object ref = dataLancamento_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dataLancamento_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string data_lancamento = 10;</code>
       */
      public com.google.protobuf.ByteString
          getDataLancamentoBytes() {
        java.lang.Object ref = dataLancamento_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataLancamento_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string data_lancamento = 10;</code>
       */
      public Builder setDataLancamento(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        dataLancamento_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string data_lancamento = 10;</code>
       */
      public Builder clearDataLancamento() {
        bitField0_ = (bitField0_ & ~0x00000200);
        dataLancamento_ = getDefaultInstance().getDataLancamento();
        onChanged();
        return this;
      }
      /**
       * <code>required string data_lancamento = 10;</code>
       */
      public Builder setDataLancamentoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        dataLancamento_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:representacaoexternaBuffer.Gerenciamento)
    }

    // @@protoc_insertion_point(class_scope:representacaoexternaBuffer.Gerenciamento)
    private static final representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento();
    }

    public static representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Gerenciamento>
        PARSER = new com.google.protobuf.AbstractParser<Gerenciamento>() {
      @java.lang.Override
      public Gerenciamento parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Gerenciamento(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Gerenciamento> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Gerenciamento> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public representacaoexternaBuffer.GerenciamentoOuterClass.Gerenciamento getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DimensaoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:representacaoexternaBuffer.Dimensao)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float altura = 1;</code>
     */
    boolean hasAltura();
    /**
     * <code>required float altura = 1;</code>
     */
    float getAltura();

    /**
     * <code>required float largura = 2;</code>
     */
    boolean hasLargura();
    /**
     * <code>required float largura = 2;</code>
     */
    float getLargura();

    /**
     * <code>required float comprimento = 3;</code>
     */
    boolean hasComprimento();
    /**
     * <code>required float comprimento = 3;</code>
     */
    float getComprimento();
  }
  /**
   * Protobuf type {@code representacaoexternaBuffer.Dimensao}
   */
  public  static final class Dimensao extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:representacaoexternaBuffer.Dimensao)
      DimensaoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Dimensao.newBuilder() to construct.
    private Dimensao(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dimensao() {
      altura_ = 0F;
      largura_ = 0F;
      comprimento_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Dimensao(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              bitField0_ |= 0x00000001;
              altura_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              largura_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              comprimento_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return representacaoexternaBuffer.GerenciamentoOuterClass.internal_static_representacaoexternaBuffer_Dimensao_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return representacaoexternaBuffer.GerenciamentoOuterClass.internal_static_representacaoexternaBuffer_Dimensao_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.class, representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.Builder.class);
    }

    private int bitField0_;
    public static final int ALTURA_FIELD_NUMBER = 1;
    private float altura_;
    /**
     * <code>required float altura = 1;</code>
     */
    public boolean hasAltura() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float altura = 1;</code>
     */
    public float getAltura() {
      return altura_;
    }

    public static final int LARGURA_FIELD_NUMBER = 2;
    private float largura_;
    /**
     * <code>required float largura = 2;</code>
     */
    public boolean hasLargura() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float largura = 2;</code>
     */
    public float getLargura() {
      return largura_;
    }

    public static final int COMPRIMENTO_FIELD_NUMBER = 3;
    private float comprimento_;
    /**
     * <code>required float comprimento = 3;</code>
     */
    public boolean hasComprimento() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float comprimento = 3;</code>
     */
    public float getComprimento() {
      return comprimento_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAltura()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLargura()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasComprimento()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, altura_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, largura_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, comprimento_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, altura_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, largura_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, comprimento_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao)) {
        return super.equals(obj);
      }
      representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao other = (representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao) obj;

      boolean result = true;
      result = result && (hasAltura() == other.hasAltura());
      if (hasAltura()) {
        result = result && (
            java.lang.Float.floatToIntBits(getAltura())
            == java.lang.Float.floatToIntBits(
                other.getAltura()));
      }
      result = result && (hasLargura() == other.hasLargura());
      if (hasLargura()) {
        result = result && (
            java.lang.Float.floatToIntBits(getLargura())
            == java.lang.Float.floatToIntBits(
                other.getLargura()));
      }
      result = result && (hasComprimento() == other.hasComprimento());
      if (hasComprimento()) {
        result = result && (
            java.lang.Float.floatToIntBits(getComprimento())
            == java.lang.Float.floatToIntBits(
                other.getComprimento()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAltura()) {
        hash = (37 * hash) + ALTURA_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getAltura());
      }
      if (hasLargura()) {
        hash = (37 * hash) + LARGURA_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getLargura());
      }
      if (hasComprimento()) {
        hash = (37 * hash) + COMPRIMENTO_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getComprimento());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parseFrom(data);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parseFrom(data, extensionRegistry);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return parseFrom(data);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code representacaoexternaBuffer.Dimensao}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:representacaoexternaBuffer.Dimensao)
        representacaoexternaBuffer.GerenciamentoOuterClass.DimensaoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return representacaoexternaBuffer.GerenciamentoOuterClass.internal_static_representacaoexternaBuffer_Dimensao_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return representacaoexternaBuffer.GerenciamentoOuterClass.internal_static_representacaoexternaBuffer_Dimensao_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.class, representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.Builder.class);
      }

      // Construct using representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        altura_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        largura_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        comprimento_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return representacaoexternaBuffer.GerenciamentoOuterClass.internal_static_representacaoexternaBuffer_Dimensao_descriptor;
      }

      @java.lang.Override
      public representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao getDefaultInstanceForType() {
        return representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.getDefaultInstance();
      }

      @java.lang.Override
      public representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao build() {
        representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao buildPartial() {
        representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao result = new representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.altura_ = altura_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.largura_ = largura_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.comprimento_ = comprimento_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao) {
          return mergeFrom((representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao other) {
        if (other == representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao.getDefaultInstance()) return this;
        if (other.hasAltura()) {
          setAltura(other.getAltura());
        }
        if (other.hasLargura()) {
          setLargura(other.getLargura());
        }
        if (other.hasComprimento()) {
          setComprimento(other.getComprimento());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAltura()) {
          return false;
        }
        if (!hasLargura()) {
          return false;
        }
        if (!hasComprimento()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float altura_ ;
      /**
       * <code>required float altura = 1;</code>
       */
      public boolean hasAltura() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float altura = 1;</code>
       */
      public float getAltura() {
        return altura_;
      }
      /**
       * <code>required float altura = 1;</code>
       */
      public Builder setAltura(float value) {
        bitField0_ |= 0x00000001;
        altura_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float altura = 1;</code>
       */
      public Builder clearAltura() {
        bitField0_ = (bitField0_ & ~0x00000001);
        altura_ = 0F;
        onChanged();
        return this;
      }

      private float largura_ ;
      /**
       * <code>required float largura = 2;</code>
       */
      public boolean hasLargura() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float largura = 2;</code>
       */
      public float getLargura() {
        return largura_;
      }
      /**
       * <code>required float largura = 2;</code>
       */
      public Builder setLargura(float value) {
        bitField0_ |= 0x00000002;
        largura_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float largura = 2;</code>
       */
      public Builder clearLargura() {
        bitField0_ = (bitField0_ & ~0x00000002);
        largura_ = 0F;
        onChanged();
        return this;
      }

      private float comprimento_ ;
      /**
       * <code>required float comprimento = 3;</code>
       */
      public boolean hasComprimento() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float comprimento = 3;</code>
       */
      public float getComprimento() {
        return comprimento_;
      }
      /**
       * <code>required float comprimento = 3;</code>
       */
      public Builder setComprimento(float value) {
        bitField0_ |= 0x00000004;
        comprimento_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float comprimento = 3;</code>
       */
      public Builder clearComprimento() {
        bitField0_ = (bitField0_ & ~0x00000004);
        comprimento_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:representacaoexternaBuffer.Dimensao)
    }

    // @@protoc_insertion_point(class_scope:representacaoexternaBuffer.Dimensao)
    private static final representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao();
    }

    public static representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Dimensao>
        PARSER = new com.google.protobuf.AbstractParser<Dimensao>() {
      @java.lang.Override
      public Dimensao parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Dimensao(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dimensao> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dimensao> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public representacaoexternaBuffer.GerenciamentoOuterClass.Dimensao getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_representacaoexternaBuffer_Gerenciamento_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_representacaoexternaBuffer_Gerenciamento_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_representacaoexternaBuffer_Dimensao_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_representacaoexternaBuffer_Dimensao_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.representacaoexternaBuffer/Gerenciamen" +
      "to.proto\022\032representacaoexternaBuffer\"\326\001\n" +
      "\rGerenciamento\022\016\n\006titulo\030\001 \002(\t\022\r\n\005autor\030" +
      "\002 \002(\t\022\016\n\006cantor\030\003 \002(\t\022\013\n\003ano\030\004 \002(\005\022\022\n\nnu" +
      "m_pagina\030\005 \002(\005\022\014\n\004isbn\030\006 \002(\t\022\014\n\004peso\030\007 \002" +
      "(\002\0221\n\003dim\030\010 \002(\0132$.representacaoexternaBu" +
      "ffer.Dimensao\022\r\n\005album\030\t \002(\t\022\027\n\017data_lan" +
      "camento\030\n \002(\t\"@\n\010Dimensao\022\016\n\006altura\030\001 \002(" +
      "\002\022\017\n\007largura\030\002 \002(\002\022\023\n\013comprimento\030\003 \002(\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_representacaoexternaBuffer_Gerenciamento_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_representacaoexternaBuffer_Gerenciamento_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_representacaoexternaBuffer_Gerenciamento_descriptor,
        new java.lang.String[] { "Titulo", "Autor", "Cantor", "Ano", "NumPagina", "Isbn", "Peso", "Dim", "Album", "DataLancamento", });
    internal_static_representacaoexternaBuffer_Dimensao_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_representacaoexternaBuffer_Dimensao_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_representacaoexternaBuffer_Dimensao_descriptor,
        new java.lang.String[] { "Altura", "Largura", "Comprimento", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
