/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.sockets;

import static com.oracle.jrockit.jfr.ContentType.Bytes;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.ByteBuffer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author a899607
 */
public class JFrameConversa extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    private String nome;
    private DataOutputStream out;

    public JFrameConversa() throws IOException {
        initComponents();
        this.nome = JOptionPane.showInputDialog("Informe o seu nome:");
        TCPClient cliente = new TCPClient();
        cliente.setListener(this::setMensagem);
        cliente.connect();
        out = new DataOutputStream(cliente.clientSocket.getOutputStream());
    }

    private void setMensagem(byte[] mensagem) {        
        System.out.println("RS - Comando: " + mensagem[0]);
        System.out.println("RS - Tamanho: " + mensagem.length);
        
        if(mensagem[1] == 2){
            if(mensagem[2] == 1){
                jTodasMensagens.append("\nArquivo excluído com sucesso!");
            }else{
                jTodasMensagens.append("\nArquivo não foi excluído!");
            }            
        }else if(mensagem[1] == 3){
            byte [] tamanho = new byte[2];
            tamanho[0] = mensagem[3];
            tamanho[1] = mensagem[4];
            System.out.println("AAA: " + tamanho[0] + tamanho[1]);
            int totalArquivos = new BigInteger(tamanho).intValue();;
            jTodasMensagens.append("\nTotal de arquivos: " + totalArquivos);
            jTodasMensagens.append("\nArquivos: ");
            int posAtual = 5;
            for(int i = 0; i < totalArquivos; i++){
                int tamanhoNome = (int) mensagem[posAtual];
                byte[] nome = new byte[tamanhoNome];
                posAtual++;
                for(int j = 0; j < tamanhoNome; j++){
                    nome[j] = mensagem[posAtual++];
                }
                String nomeArquivo = new String(nome);
                jTodasMensagens.append("\n" + nomeArquivo);
            }                           
        }else if(mensagem[1] == 4){
                      
        }
        
        // String[] partes = mensagem.split("-");
        //   jTodasMensagens.append(partes[0] + " disse: " + partes[1] + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTodasMensagens = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMensagemUsuario = new javax.swing.JTextArea();
        jButtonEnviar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTodasMensagens.setEditable(false);
        jTodasMensagens.setColumns(20);
        jTodasMensagens.setRows(5);
        jScrollPane1.setViewportView(jTodasMensagens);

        jMensagemUsuario.setColumns(20);
        jMensagemUsuario.setRows(5);
        jMensagemUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMensagemUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jMensagemUsuarioKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jMensagemUsuario);

        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        try {
            String mensagem = "\n" + jMensagemUsuario.getText();

            byte[] array;
           // System.out.println("TAM :" + mensagem.split(" ")[1].getBytes().length);
            int k = 3;
            if (!mensagem.contains("GETFILESLIST")) {
                array = new byte[mensagem.split(" ")[1].getBytes().length+3];
                byte[] nomeArq = mensagem.split(" ")[1].getBytes();
                array[2] = (byte) nomeArq.length;
                int tamanho = mensagem.split(" ")[1].getBytes().length;
                for (int j = 0; j < tamanho; j++) {
                    array[k++] = nomeArq[j];
                }
            }else{
                array = new byte[2];
            }
            
            array[0] = 1;
             
            if (mensagem.contains("DELETE")) {
                array[1] = 2;
            } else if (mensagem.contains("GETFILESLIST")) {
                array[1] = 3;
            } else if (mensagem.contains("GETFILE")) {
                array[1] = 4;
            }
            System.out.println("C - Comando: " + array[1]);
            System.out.println("C - Tamanho: " + array.length);

            out.write(array);
            jTodasMensagens.append(this.nome + " disse: " + jMensagemUsuario.getText() + "\n");
            jMensagemUsuario.setText("");
        } catch (IOException ex) {
            Logger.getLogger(JFrameConversa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jMensagemUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMensagemUsuarioKeyReleased

    }//GEN-LAST:event_jMensagemUsuarioKeyReleased

    private void jMensagemUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMensagemUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonEnviarActionPerformed(null);
        }
    }//GEN-LAST:event_jMensagemUsuarioKeyPressed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameConversa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameConversa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameConversa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameConversa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameConversa().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(JFrameConversa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JTextArea jMensagemUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTodasMensagens;
    // End of variables declaration//GEN-END:variables
}
